apiVersion: v1
kind: ConfigMap
metadata:
  name: aeza-backend-config
  namespace: logovizor
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  SERVER_PORT: "8087"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logovizor
  SPRING_DATASOURCE_USERNAME: postgres
  OPENSEARCH_ENABLED: "true"
  OPENSEARCH_URL: http://opensearch:9200
  OPENSEARCH_INDEX_PREFIX: log-events
  ALERT_SCHEDULER_INTERVAL_MS: "30000"
  SPRINGDOC_SWAGGER_UI_PATH: /docs
  SPRINGDOC_SWAGGER_UI_URL: /openapi.yaml
  SPRINGDOC_SWAGGER_UI_DISABLE_SWAGGER_DEFAULT_URL: "true"
  SPRINGDOC_API_DOCS_PATH: /docs/openapi
