apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logovizor
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - opensearch-pvc.yaml
  - postgres.yaml
  - opensearch.yaml
  - backend.yaml
