apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: logovizor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.19.1
          args:
            - opensearch
            - -Ediscovery.type=single-node
            - -Eplugins.security.disabled=true
          ports:
            - containerPort: 9200
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aeza-backend-secret
                  key: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
          readinessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: opensearch-data
          persistentVolumeClaim:
            claimName: opensearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: logovizor
spec:
  selector:
    app: opensearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
