apiVersion: v1
kind: Secret
metadata:
  name: aeza-backend-secret
  namespace: logovizor
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: change-me
  OPENSEARCH_USERNAME: ""
  OPENSEARCH_PASSWORD: ""
  INTEGRATION_TELEGRAM_BOT_TOKEN: ""
  INTEGRATION_TELEGRAM_CHAT_ID: ""
  INTEGRATION_WEBHOOK_URL: ""
  POSTGRES_PASSWORD: change-me
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: StrongPass_12345
