ALTER TABLE log_events
    ALTER COLUMN host TYPE VARCHAR(2048),
    ALTER COLUMN service TYPE VARCHAR(2048),
    ALTER COLUMN source_type TYPE VARCHAR(255),
    ALTER COLUMN source_path TYPE VARCHAR(4096),
    ALTER COLUMN agent_id TYPE VARCHAR(255);
